// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT0NHYEPdzLdEfcz175r00AkSsKHjNTFs',
    appId: '1:696852908136:web:582a576c22e754f99693dd',
    messagingSenderId: '696852908136',
    projectId: 'qyzbolsyn-app-15',
    authDomain: 'qyzbolsyn-app-15.firebaseapp.com',
    storageBucket: 'qyzbolsyn-app-15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAkWl3TAEuquYzQNJAAYMG_wTMtDwU7TY',
    appId: '1:696852908136:android:8c6bb3c0f2e9cc419693dd',
    messagingSenderId: '696852908136',
    projectId: 'qyzbolsyn-app-15',
    storageBucket: 'qyzbolsyn-app-15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZWizb6v9SEvaxWfyTYEOU8NrGtnLDK8A',
    appId: '1:696852908136:ios:2e2eb917f79151609693dd',
    messagingSenderId: '696852908136',
    projectId: 'qyzbolsyn-app-15',
    storageBucket: 'qyzbolsyn-app-15.appspot.com',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZWizb6v9SEvaxWfyTYEOU8NrGtnLDK8A',
    appId: '1:696852908136:ios:2e2eb917f79151609693dd',
    messagingSenderId: '696852908136',
    projectId: 'qyzbolsyn-app-15',
    storageBucket: 'qyzbolsyn-app-15.appspot.com',
    iosBundleId: 'com.example.last',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT0NHYEPdzLdEfcz175r00AkSsKHjNTFs',
    appId: '1:696852908136:web:b03fd717cae6af0e9693dd',
    messagingSenderId: '696852908136',
    projectId: 'qyzbolsyn-app-15',
    authDomain: 'qyzbolsyn-app-15.firebaseapp.com',
    storageBucket: 'qyzbolsyn-app-15.appspot.com',
  );
}
